### ISSUE TITLE
Not created volume

### ISSUE THREAD

**Issue by 2mind** [disaster37/rancher-glusterfs-server#1]
Hello, disaster37.
I Have some problems:

I am dev_gluster2_1 and my IP is 10.42.132.188
There are 2 container is this service
I am not yet on cluster
There are no cluster. I will get if I am the master
I will create the new cluster
dev_gluster2_2 ( 10.42.143.224 )  added on cluster
I will create all volumes
volume create: ranchervol: failed: Host 10.42.143.224 is not in 'Peer in Cluster' state
Some error appear :
## Nothing...

I don't use device binding /dev/fuse...empty by default and volume ranchvol

**Comment by 2mind** [comment]
fix
add too time.sleep before volume_manager.create

**Comment by disaster37** [comment]
I will fix the code ASAP. The best way I think, is to check that the host is in the cluster before start the creation of the volumes.

If not make infinite loop with a sleep of few second

**Comment by disaster37** [comment]
Try the last image version, it's normaly fix your problem.

docker pull quay.io/webcenter/rancher-glusterfs-server:latest
Clone your current stack or create new stack with this image quay.io/webcenter/rancher-glusterfs-server:latest

Can you say me if it's better ?

**Comment by 2mind** [comment]
Thx.
It's better.
But, i use:
containers = metadata_manager.wait_service_containers()...and count. And not use scale size.

## Tagging (schedule) hosts.

And i not really undestand gluster)
...create  basic cluster 2 node (type replicate) and then destroy(docker rm & rmi -f) second node. rancher service it goes to the state degree...Rancher service recreate container with another ip and add to volume cluster, but destroy node do not delete. Yes, peers status show - second node is disconnect. I have to remove the brick and then do the rebalancing?

**Comment by disaster37** [comment]
Fore the moment, we can only add new container, and it will extend automaticaly the cluster.
For upgrade container et remove container, you must doing that with the hand (and it can be so difficult)
